![](1.jpg)

# Лабораторная Работа №4

# Прогоним симмуляцию сети петри
![](3.jpg)
<br>
Диаграмма маркировок:
<br>
![](4.jpg)

Из симмуляции сети сожно сделать предлоположения о характеристиках сети:

<ul>
<li><input type="checkbox" checked> Безопасная</li>
<li><input type="checkbox" checked>1-консервативная </li>
<li><input type="checkbox" checked>консервативная</li>
</ul>

![](8.png)

![](9.png)

In [6]:
import numpy as np

D_input = np.array([
    [1,0,0,0,0,0],
    [0,1,0,0,0,0],
    [0,0,1,0,0,0],
    [0,0,0,1,1,1]])
D_output = np.array([
    [0,1,1,0,0,1],
    [0,0,0,1,0,0],
    [0,0,0,0,1,0],
    [1,0,0,0,0,0]])

Incidence_D = D_output - D_input
print(Incidence_D)

[[-1  1  1  0  0  1]
 [ 0 -1  0  1  0  0]
 [ 0  0 -1  0  1  0]
 [ 1  0  0 -1 -1 -1]]


In [20]:
'''
import copy
import scipy

def check_if_safe(D):
    try:
        print(np.linalg.lstsq(D, np.zeros(D.shape[0]),rcond=None))
        return True
    except:
        return False

def check_if_can_be_reach(_n_1,_n_2,D):
    n_1 = np.array(_n_1)
    n_2 = np.array(_n_2)
    n_diif = n_2 - n_1
    try:
        f = np.linalg.solve(D,n_diif)
        return True,f
    except:
        return False


def step(n,D_I):
    rows_to_return = []
    for i,row in enumerate(D_I):
        if np.all(n >= row):
            rows_to_return.append()
    return rows_to_return
            
def check_for_parallel(_n_0,D_I,D):
    N = 100
    next_steps = [_n_0,]
    n = 0
    while n < N and len(current_vector)!=0:
        current_vector = next_steps.pop()
        steps = step(current_vector,D_I)
        if len(steps) == 0:
            return
        if len(steps) > 1:
            for i in range(len(steps)):
                for j in range(i+1,len(steps)):
                    f_st_input_vector =current_vector *D_I[steps[i]]
                    s_nd_input_vector =current_vector * D_I[steps[j]]
                    result_vector = f_st_input_vector + s_nd_input_vector
                    if np.all(current_vector >= result_vector):
                        return True, current_vector
        [next_steps.append(current_vector+D[i]) for i in steps]
    return False


print(f"Является сохраняющей: {check_if_safe(Incidence_D)}")
print(f"Явдяется ли достижимой: {check_if_can_be_reach()}")


'''

(array([0., 0., 0., 0., 0., 0.]), array([], dtype=float64), 3, array([2.44948974e+00, 2.00000000e+00, 1.41421356e+00, 9.60895038e-17]))
Является сохраняющей: True
